In [26]:
from numpy import convolve, negative, power, exp, divide, multiply, sum

In [20]:
def get_kernel(window_width: int, sigma: int) -> list:
    """
    Parameters
    -------
    window_width: list
        List of intervals for gaussian window
    sigma: int
        Standard deviation or "width" of gaussian curve
    Returns
    -------
    normalised kernel of gaussian window
    """
    x = [*range(-window_width, window_width + 1)]
    kernel = exp(divide(power(negative(x), 2), 2 * power(sigma, 2)))
    kernel = kernel / sum(kernel)

    return kernel

In [21]:
kernel_made = get_kernel(3, 2)
kernel_made

array([0.24207599, 0.12957394, 0.08905478, 0.07859057, 0.08905478,
       0.12957394, 0.24207599])

In [22]:
mid_index = int(len(kernel_made)/2)
mid_index

3

In [28]:
left = []
radii = [1.25768,1.17432,1.14639,1.19582,1.16848,1.18433,1.13193,1.15015,1.12888,1.20616,1.22181,1.14383,1.14451,1.07132,1.14595,1.26909,1.50458,1.44053,]

for i in range(0,mid_index-2):
    tmp_filter = kernel_made[mid_index-i:]
    print(tmp_filter)
    tmp_filter = divide(tmp_filter, sum(tmp_filter))
    print(tmp_filter)
    multiplied = multiply(radii[:mid_index+i], tmp_filter)
    convolved = sum(multiplied)
    print(convolved)
    left.append(convolved)

left

[0.07859057 0.08905478 0.12957394 0.24207599]
[0.14572827 0.16513176 0.2402653  0.44887467]


ValueError: operands could not be broadcast together with shapes (3,) (4,) 